CREATE TABLE IF NOT EXISTS IDN_ORG_CONNECTION_ASSOCIATION (
    ID                       INTEGER     NOT NULL AUTO_INCREMENT,
    RESOURCE_TYPE            VARCHAR(255) NOT NULL,
    SHARED_RESOURCE_UUID     CHAR(36)    NOT NULL,
    SHARED_ORG_ID            CHAR(36)    NOT NULL,
    ASSOCIATED_CONNECTION_UUID CHAR(36)    NOT NULL,
    ASSOCIATED_ORG_ID        CHAR(36)    NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (SHARED_RESOURCE_UUID)
);
