CREATE TABLE IF NOT EXISTS UM_ORG_USER_ASSOCIATION (
    UM_ID INTEGER NOT NULL AUTO_INCREMENT,
    UM_USER_ID VARCHAR(255) NOT NULL,
    UM_ORG_ID VARCHAR(255) NOT NULL,
    UM_ASSOCIATED_USER_ID VARCHAR(255) NOT NULL,
    UM_ASSOCIATED_ORG_ID VARCHAR(255) NOT NULL,
    UM_SHARED_TYPE VARCHAR(50),
    PRIMARY KEY (UM_ID)
);
