-- ---------------------------------------------------------------------------
-- Table: UM_USER
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS UM_USER (
    UM_ID INTEGER NOT NULL AUTO_INCREMENT,
    UM_USER_ID VARCHAR(255) NOT NULL,
    UM_USER_NAME VARCHAR(255) NOT NULL,
    UM_USER_PASSWORD VARCHAR(255) NOT NULL,
    UM_SALT_VALUE VARCHAR(31),
    UM_REQUIRE_CHANGE BOOLEAN DEFAULT FALSE,
    UM_CHANGED_TIME TIMESTAMP NOT NULL,
    UM_TENANT_ID INTEGER DEFAULT 0,
    PRIMARY KEY (UM_ID, UM_TENANT_ID),
    UNIQUE(UM_USER_ID),
    UNIQUE(UM_USER_NAME, UM_TENANT_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS INDEX_UM_USERNAME_UM_TENANT_ID ON UM_USER(UM_USER_NAME, UM_TENANT_ID);
-- ---------------------------------------------------------------------------
-- Table: UM_ORG_USER_ASSOCIATION
-- Mirrors the user-sharing UM_ORG_USER_ASSOCIATION table. Stores the
-- association between a shared user and the organizations it is shared into.
-- UM_ASSOCIATED_USER_ID / UM_ASSOCIATED_ORG_ID identify the original (root)
-- user, while UM_USER_ID / UM_ORG_ID identify the shared user entry in the
-- target organization.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS UM_ORG_USER_ASSOCIATION (
    UM_ID                  INTEGER      NOT NULL AUTO_INCREMENT,
    UM_USER_ID             VARCHAR(255) NOT NULL,
    UM_ORG_ID              VARCHAR(36)  NOT NULL,
    UM_ASSOCIATED_USER_ID  VARCHAR(255) NOT NULL,
    UM_ASSOCIATED_ORG_ID   VARCHAR(36)  NOT NULL,
    UM_SHARED_TYPE         VARCHAR(255) NOT NULL DEFAULT 'NOT SPECIFIED',
    PRIMARY KEY (UM_USER_ID, UM_ORG_ID, UM_ASSOCIATED_USER_ID, UM_ASSOCIATED_ORG_ID),
    UNIQUE (UM_ID),
    CONSTRAINT FK_UM_OUA_USER_ID FOREIGN KEY (UM_USER_ID) REFERENCES UM_USER(UM_USER_ID)
);

CREATE INDEX IF NOT EXISTS IDX_UM_OUA_USER_ID       ON UM_ORG_USER_ASSOCIATION (UM_USER_ID);
CREATE INDEX IF NOT EXISTS IDX_UM_OUA_ORG_ID        ON UM_ORG_USER_ASSOCIATION (UM_ORG_ID);
CREATE INDEX IF NOT EXISTS IDX_UM_OUA_ASSOC_USER_ID ON UM_ORG_USER_ASSOCIATION (UM_ASSOCIATED_USER_ID);
CREATE INDEX IF NOT EXISTS IDX_UM_OUA_ASSOC_ORG_ID  ON UM_ORG_USER_ASSOCIATION (UM_ASSOCIATED_ORG_ID);
